### ISSUE TITLE
google.com:<name> should be a valid project name to instantiate PathTemplate

### ISSUE THREAD

**Issue by geigerj** [googleapis/gax-python#39]
Tried to instantiate PathTemplate, but it fails with the following stack trace:

ERROR:root:match error: impossible match
Traceback (most recent call last):
  File "example.py", line 14, in run
    project_name = PubApi.project_path(project_id)
  File "/usr/local/google/home/jgeiger/xnewgitonborg/gapi-dev/gapi-pubsub-python/gcloud/pubsub/publisher_api.py", line 57, in project_path
    return cls._PROJECT_PATH_TEMPLATE.instantiate({'project': project, })
  File "/usr/local/google/home/jgeiger/xnewgitonborg/gapi-dev/gapi-pubsub-python/.tox/py27/local/lib/python2.7/site-packages/google/gax/path_template.py", line 125, in\
 instantiate
    self.match(path)
  File "/usr/local/google/home/jgeiger/xnewgitonborg/gapi-dev/gapi-pubsub-python/.tox/py27/local/lib/python2.7/site-packages/google/gax/path_template.py", line 170, in\
 match
    raise ValidationException('match error: impossible match')
ValidationException: match error: impossible match

**Comment by saicheems** [comment]
What's the template string?

**Comment by geigerj** [comment]
google.com:<project_id>
